Optimized normal inference results confidence interval method speed
py-why/EconML pull request #879
Opened 2024-05-01 00:56 UTC by gdaiha

Optimized NormalInferenceResults.conf_int method speed, replacing a unnecessary loop by the main usage of scipy.stats.norm.ppf function. This allows big inputs to be calculated at least 50x faster (conservative estimation).

2024-05-01 19:19 UTC, kbattocchi requested changes
Thanks for the contribution!  If `_safe_norm_ppf` already correctly handles arrays as inputs, could you also change the other places that we're doing this unnecessary zipping as part of this PR?  Specifically, `PopulationSummaryResults.conf_int_mean` in _inference.py, and `_StatsModelsWrapper.coef__interval`, `_StatsModelsWrapper.intercept__interval`, and `_StatsModelsWrapper.predict_interval` in linear_model.py.

2024-05-03 18:08 UTC, gdaiha commented
Some tests are having unstable results.

2024-05-03 18:29 UTC, kbattocchi commented
@gdaiha Recent changes to the GitHub `macos-latest` runner have broken our Mac tests; don't worry about addressing that yourself, but you'll have to merge in our fix once it hits main later today.  Some of our other tests are occasionally flaky, but we can rerun them if we see a spurious failure.

2024-05-03 18:30 UTC, kbattocchi approved these changes

2024-05-04 05:19 UTC, kbattocchi commented
> @gdaiha Recent changes to the GitHub `macos-latest` runner have broken our Mac tests; don't worry about addressing that yourself, but you'll have to merge in our fix once it hits main later today. Some of our other tests are occasionally flaky, but we can rerun them if we see a spurious failure.

We've run into some unanticipated making these fixes to the build system - I'll take care of merging them into this branch once they're ready.  Thanks again for your contribution!

2024-05-07 08:23 UTC, merged