fix bug in check_high_dimensional
py-why/EconML pull request #906
Opened 2024-08-05 08:38 UTC by itamarfaran

2024-08-05 08:39 UTC, itamarfaran commented
https://github.com/py-why/EconML/issues/905

2024-08-11 22:08 UTC, kbattocchi requested changes
Thanks for the contribution! Please add a test that would fail without your fix.

2024-08-12 07:27 UTC, itamarfaran commented
added :)

2024-08-14 08:30 UTC, kbattocchi approved these changes

2024-08-14 08:31 UTC, merged