"Fixes linear DRIV shape inconsistency"
py-why/EconML pull request #920
Opened 2024-09-10 18:48 UTC by ssemov

Addresses the shape inconsistency in the linear DRIV implementation.  

**Changes:**

- I modified the [effect_interval](https://github.com/py-why/EconML/blob/960c0dd832943b8098d50f7b658cea49c822c31c/econml/inference/_inference.py#L284C1-L285C47) computation in LinearModelFinalInference class. This is where the inference method for LinearDRIV comes from.
- I added the modification function - reshape_outcomewise_effects - to utilities. Given an effects matrix, it reshapes the second dimension to be consistent with d_y[0]. 

**Related [issue]**(https://github.com/py-why/EconML/issues/687).  

**Testing:**

- TestDRIV --> OK
- test_inference --> OK
- test_statsmodels --> OK

2024-09-13 18:59 UTC, kbattocchi commented
Thanks for the contribution.  Unfortunately, these changes are causing test failures in `econml.tests.test_dml.TestDML.test_ignores_final_intercept`, `econml.tests.test_discrete_outcome.TestDiscreteOutcome.test_accuracy`, and `econml.tests.test_discrete_outcome.TestDiscreteOutcome.test_accuracy_iv`.

Given that the shapes are as expected for other estimators (like `LinearDML`) using the same inference class, I think the best place to address the problem is probably somewhere in [_dr.py](https://github.com/py-why/EconML/blob/main/econml/iv/dr/_dr.py), although maybe there is a way to address it in the inference class that doesn't break other classes that use it.

2024-09-13 20:59 UTC, ssemov commented
Thanks, @kbattocchi! yes, I think the fix I have touches too many things. I'll look into something more local in [_dr.py](https://github.com/py-why/EconML/blob/main/econml/iv/dr/_dr.py).

2024-09-25 16:25 UTC, ssemov commented
@kbattocchi I made the change more local and fixed an edge case with the discrete outcome. The new version passes the tests I was failing before.

2024-10-02 18:12 UTC, kbattocchi commented on econml/inference/_inference.py
> +        return self.effect_inference(X, T0=T0, T1=T1).conf_int(alpha=alpha)
Isn't this identical to what the base class is already doing?

2024-10-02 23:05 UTC, ssemov commented
@kbattocchi Removed the redundant effect_interval method.

2024-10-03 19:32 UTC, kbattocchi requested changes
Thanks for trying again, but I don't think StatsModelsInference is the right place for the change - see my comment.

2024-10-03 19:32 UTC, kbattocchi commented on econml/inference/_inference.py
> +        e_stderr = reshape_outcomewise_effects(self._prediction_stderr(XT), self._d_y)
(And I think you'll find that without fixing the change in LinearModelFinalInference, other DRIV subclasses like SparseLinearDRIV still suffer from the same issue - please consider modifying [line 457 of test_treatment_featurization](https://github.com/py-why/EconML/blob/960c0dd832943b8098d50f7b658cea49c822c31c/econml/tests/test_treatment_featurization.py#L456-L457) to enable further tests on DRIV subclasses)

2024-10-03 20:41 UTC, ssemov commented on econml/inference/_inference.py
> +        e_stderr = reshape_outcomewise_effects(self._prediction_stderr(XT), self._d_y)
@kbattocchi Thanks, Keith, for the help. It makes sense what you are saying, I will work on a fix.

2024-10-13 22:21 UTC, ssemov commented
Changes:

- Moves the fix to LinearModelFinalInference
- updates TestTreatmentFeaturization not to skip LinearDRIV and SparseLinearDRIV

Tests:

- TestDML.test_ignores_final_intercept
- TestDiscreteOutcome.test_accuracy 
- TestDiscreteOutcome.test_accuracy_iv 
- TestTreatmentFeaturization

2024-10-16 17:18 UTC, kbattocchi approved these changes
Looks good, thanks!

2024-10-16 17:19 UTC, merged